#!/bin/bash

nbtext="{
 \"cells\": [
  {
   \"cell_type\": \"code\",
   \"execution_count\": null,
   \"metadata\": {},
   \"outputs\": [],
   \"source\": [
    \"# Imports\n\",
    \"import os\n\",
    \"import sys\n\",
    \"import glob\n\",
    \"import json\n\",
    \"import pickle\n\",
    \"import collections\n\",
    \"\n\",
    \"import tqdm\n\",
    \"import jutils\n\",
    \"import numpy as np\n\",
    \"import pandas as pd\n\",
    \"import matplotlib.pyplot as plt\"
   ]
  },
  {
   \"cell_type\": \"code\",
   \"execution_count\": null,
   \"metadata\": {},
   \"outputs\": [],
   \"source\": []
  }
 ],
 \"metadata\": {
  \"kernelspec\": {
   \"display_name\": \"Python 3\",
   \"language\": \"python\",
   \"name\": \"python3\"
  },
  \"language_info\": {
   \"codemirror_mode\": {
    \"name\": \"ipython\",
    \"version\": 3
   },
   \"file_extension\": \".py\",
   \"mimetype\": \"text/x-python\",
   \"name\": \"python\",
   \"nbconvert_exporter\": \"python\",
   \"pygments_lexer\": \"ipython3\",
   \"version\": \"3.7.3\"
  }
 },
 \"nbformat\": 4,
 \"nbformat_minor\": 4
}
"


DIR=~/Code/Start
if [ -d $DIR ]; then
    cd $DIR
else
    echo 'DIR does not exist'
    exit 1
fi

if [ $# -eq 0 ]; then
    echo "Command requires at least 1 argument [testname]"
    exit 1
fi

if [ -d "$1" ]; then
    echo "$1 dir already exists"
    exit 1
else
    mkdir $1
    cd $1
    touch test.ipynb
    echo "$nbtext" > test.ipynb
    jupyter lab --port 4404
fi
