#!/bin/bash

DIR=~/.bash_it/myscripts
if [ -d $DIR ]; then
	cd $DIR
else
	echo 'DIR does not exist'
	exit 1
fi


if [ $# -eq 0 ]; then
	echo "Command requires at least 1 argument [filename]"
	exit 1
fi

if [ -f "$1" ]; then
	echo "$1 script already exists"
	exit 1
else
	touch $1
	chmod 755 $1
	echo "#!/bin/bash" > $1
	txt $DIR
	txt $1
fi
