#!/bin/bash

cd ~/.bash_it/myscripts

if [ $# -eq 0 ]; then
	echo "Command requires at least 1 argument [filename]"
else
	if [ -f "$1" ]; then
		echo "$1 script already exists"
	else
		touch $1
		chmod 755 $1
		echo "#!/bin/bash" > $1
		myscripts
		txt $1
	fi
fi