#!/bin/bash

DIR=~/Code/Start
if [ -d $DIR ]; then
	cd $DIR
else
	echo 'DIR does not exist'
	exit 1
fi


if [ $# -eq 0 ]; then
	echo "Command requires at least 1 argument [testname]"
	exit 1
fi

if [ -d "$1" ]; then
	echo "$1 dir already exists"
	exit 1
else
	mkdir $1
	cd $1
	txt .
	txt test.py
fi
